DECLARE
    -- VARIABLE DECLARATION
    MESSAGE VARCHAR2(20) := 'HELLO, WORLD!';

BEGIN
    /*
     *  PL/SQL EXECUTABLE STATEMENT(S)
     */
    DBMS_OUTPUT.PUT_LINE (MESSAGE);

END;

/
