DECLARE
    SUBTYPE UNAME IS CHAR(20);
    SUBTYPE MESSAGE IS VARCHAR2(100);
    SALUTATION UNAME;
    GREETINGS MESSAGE;

BEGIN
    SALUTATION := 'READER';
    GREETINGS := 'WELCOME TO THE WORLD OF PL/SQL';
    DBMS_OUTPUT.PUT_LINE('HELLO ' || SALUTATION || GREETINGS);
END;
/
