\! cls
DROP DATABASE p2;
CREATE DATABASE p2;
USE p2;
CREATE TABLE student(
	ADM_NO		INTEGER		NOT NULL	UNIQUE	PRIMARY KEY,
	NAME		VARCHAR(20)	NOT NULL,
	TEST_VAR	INTEGER,
	FEE_STATUS	CHAR(8)		CHECK (FEE_STATUS = 'PAID' OR FEE_STATUS = 'NOT PAID')
);
DESC student;
INSERT INTO student(ADM_NO, NAME, FEE_STATUS) VALUES
	(8119, "A", "PAID");
-- UNIQUE VIOLATION
INSERT INTO student(ADM_NO, NAME, FEE_STATUS) VALUES
	(8119, "A", "PAID");
-- NOT NULL VIOLATION
INSERT INTO student(ADM_NO, NAME, FEE_STATUS) VALUES
	(8120, NULL, "PAID");
-- CHECK VIOLATION
INSERT INTO student(ADM_NO, NAME, FEE_STATUS) VALUES
	(8120, "B", "!@#$%^&*");
INSERT INTO student(ADM_NO, NAME, FEE_STATUS) VALUES
	(8121, "C", "NOT PAID");
SELECT * FROM student;
CREATE TABLE test(
	ADM_NO  INTEGER,
	NAME	VARCHAR(20)	NOT NULL,
	ID 		INTEGER		NOT NULL	UNIQUE	PRIMARY KEY,
	MARKS	INTEGER		DEFAULT 0	CHECK (MARKS <= 100),
	CONSTRAINT	FOREIGN KEY(ADM_NO) REFERENCES student(ADM_NO)
);
DESC test;
INSERT INTO test(ADM_NO, NAME, ID, MARKS) VALUES
	(8119, "A", 100, 50);
-- FOREIGN KEY VIOLATION
INSERT INTO test(ADM_NO, NAME, ID, MARKS) VALUES
	(8120, "C", 105, 60);
INSERT INTO test(ADM_NO, NAME, ID, MARKS) VALUES
	(8121, "B", 110, DEFAULT);
SELECT * FROM test;